### ISSUE TITLE
Transformation fails if more than one root element exists

### ISSUE THREAD

**Issue by json-uk** [markgoodyear/postcss-vertical-rhythm#1]
I've noticed that if there's more than one `rootSelector` transformation fails with a `Font declaration not found in body`. I believe the reason for this is the plugin does not collect and match multiple elements.

**Comment by markgoodyear** [comment]
Thanks @json-uk — I'll take a look into this.

**Comment by markgoodyear** [comment]
This should be now working as expected. Let me know if you run into any further issues.

**Comment by json-uk** [comment]
@markgoodyear thanks for turning this around so quickly
